In [1]:
import pandas as pd
df=pd.read_csv(r"C:\City Bike\data\external\nyc_weather.csv")
df

,time,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m
0,2024-06-01 00:00:00,15.9,52,0.0,10.4
1,2024-06-01 01:00:00,14.4,58,0.0,9.2
2,2024-06-01 02:00:00,13.7,61,0.0,8.9
3,2024-06-01 03:00:00,13.2,63,0.0,8.7
4,2024-06-01 04:00:00,13.3,61,0.0,10.3
...,...,...,...,...,...
2203,2024-08-31 19:00:00,23.5,74,0.0,14.7
2204,2024-08-31 20:00:00,22.4,81,0.0,12.6
2205,2024-08-31 21:00:00,21.9,88,0.0,10.9
2206,2024-08-31 22:00:00,21.8,87,0.0,10.8
2207,2024-08-31 23:00:00,21.6,88,0.0,10.1

In [2]:
df=pd.read_csv("C:\City Bike\data\external\station_information.csv")
df

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\Chinmaya Harekrishna\AppData\Local\Temp\ipykernel_22152\3696072026.py:1: SyntaxWarning: invalid escape sequence '\C'
  df=pd.read_csv("C:\City Bike\data\external\station_information.csv")

,station_id,name,short_name,lon,lat,region_id,capacity,rental_uris,rental_methods,has_kiosk,station_type,external_id,electric_bike_surcharge_waiver,eightd_station_services,eightd_has_key_dispenser
0,2250953816197165238,New Lots Ave & Van Sinderen Ave,3565.07,-73.899150,40.659230,71.0,16,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",False,classic,2250953816197165238,False,[],False
1,18eccc71-66be-4e4c-8335-095a9bf0df94,Adam Clayton Powell Blvd & W 126 St,7738.04,-73.947765,40.809495,71.0,33,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,18eccc71-66be-4e4c-8335-095a9bf0df94,False,[],False
2,1822663031356509142,Matthews Ct & Coney Island Ave,3034.02,-73.969510,40.642350,71.0,0,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,1822663031356509142,False,[],False
3,7a6fc75f-a605-4dd6-b567-b2bbbfb862f3,65 Pl & 53 Ave,5764.02,-73.900220,40.731450,71.0,19,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,7a6fc75f-a605-4dd6-b567-b2bbbfb862f3,False,[],False
4,2235294222661977076,Livonia Ave & Powell St,3678.05,-73.902310,40.663630,71.0,0,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",False,classic,2235294222661977076,False,[],False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2515,66ddd93e-0aca-11e7-82f6-3863bb44ef7c,Jersey & 6th St,JC027,-74.045572,40.725289,70.0,14,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,66ddd93e-0aca-11e7-82f6-3863bb44ef7c,False,[],False
2516,9d344652-976b-4c2d-bede-2ef19b0fbf13,6 St & Grand St,HB302,-74.034501,40.744398,311.0,18,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,9d344652-976b-4c2d-bede-2ef19b0fbf13,False,[],False
2517,519824e4-69ba-4270-a395-17c204f328f8,8 St & Washington St,HB603,-74.028199,40.745984,311.0,21,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,519824e4-69ba-4270-a395-17c204f328f8,False,[],False
2518,66ddd8a8-0aca-11e7-82f6-3863bb44ef7c,Brunswick & 6th,JC081,-74.050389,40.726012,70.0,14,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,66ddd8a8-0aca-11e7-82f6-3863bb44ef7c,False,[],False
2519,66ddddb4-0aca-11e7-82f6-3863bb44ef7c,Monmouth & 6th,JC075,-74.048790,40.725685,70.0,14,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,66ddddb4-0aca-11e7-82f6-3863bb44ef7c,False,[],False

In [3]:
df1=pd.read_csv(r"C:\City Bike\data\raw\202608-citibike-tripdata_1.csv")
df1

C:\Users\Chinmaya Harekrishna\AppData\Local\Temp\ipykernel_22152\418552038.py:1: DtypeWarning: Columns (0: end_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df1=pd.read_csv(r"C:\City Bike\data\raw\202608-citibike-tripdata_1.csv")

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,40.744876,-73.995299,member
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,40.744876,-73.995299,member
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,40.744876,-73.995299,member
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,F6BF9BCE6F55D550,classic_bike,2026-08-14 18:13:56.541,2026-08-14 18:37:11.714,31 Ave & 34 St,6819.15,45 Ave & 21 St,6319.07,40.763154,-73.920827,40.747371,-73.947773,casual
999996,298BCE42846A999F,classic_bike,2026-08-05 12:56:35.603,2026-08-05 13:02:28.249,W 63 St & Broadway,7052.01,W 50 St & 9 Ave,6854.05,40.771639,-73.982614,40.763605,-73.989180,casual
999997,4D6FDAFC8218B083,electric_bike,2026-08-11 21:54:03.077,2026-08-11 22:05:10.924,Ditmars Blvd & 43 St,7039.03,Crescent St & 30 Ave,6958.06,40.771203,-73.903865,40.768692,-73.924957,casual
999998,9469A96109EE6A09,electric_bike,2026-08-01 05:34:51.238,2026-08-01 05:40:49.970,Ave D & E 3 St,5436.09,Ave A & E 14 St,5779.11,40.720828,-73.977932,40.730311,-73.980472,casual
999999,BD78D2BBCABC73EF,electric_bike,2026-08-01 13:59:25.871,2026-08-01 14:12:11.756,St Marks Pl & 4 Ave,4249.01,3 St & Prospect Park West,3865.05,40.681970,-73.980340,40.668132,-73.973638,member

In [4]:
df2=pd.read_csv(r"C:\City Bike\data\raw\202608-citibike-tripdata_2.csv")
df2

C:\Users\Chinmaya Harekrishna\AppData\Local\Temp\ipykernel_22152\4247512794.py:1: DtypeWarning: Columns (0: end_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df2=pd.read_csv(r"C:\City Bike\data\raw\202608-citibike-tripdata_2.csv")

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,AE74944C8277552A,classic_bike,2026-08-13 11:15:19.068,2026-08-13 11:17:56.989,Monroe St & Classon Ave,4336.01,Hancock St & Bedford Ave,4255.05,40.684568,-73.958811,40.682166,-73.953990,member
1,9669210D7E9DE4F8,classic_bike,2026-08-04 15:38:37.778,2026-08-04 15:41:56.248,Monroe St & Classon Ave,4336.01,Hancock St & Bedford Ave,4255.05,40.684568,-73.958811,40.682166,-73.953990,member
2,2D800455B6943247,electric_bike,2026-08-01 12:00:03.691,2026-08-01 12:02:34.810,Fulton St & Irving Pl,4263.12,Hancock St & Bedford Ave,4255.05,40.681860,-73.959432,40.682166,-73.953990,member
3,E33007CF83E516E7,electric_bike,2026-08-12 14:48:23.583,2026-08-12 15:15:21.814,Front St & Pine St,4953.08,W 50 St & 9 Ave,6854.05,40.705310,-74.006130,40.763605,-73.989180,member
4,33DB75C77C09D836,electric_bike,2026-08-11 13:45:03.829,2026-08-11 13:52:01.181,E 46 St & Madison Ave,6551.16,3 Ave & E 72 St,7028.04,40.755393,-73.977601,40.769943,-73.960607,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,827022C1EF171E71,electric_bike,2026-08-04 18:21:49.181,2026-08-04 18:29:28.704,E 149 St & Morris Ave,7863.03,Alexander Ave & E 134 St,7712.04,40.817340,-73.922962,40.807466,-73.927107,member
999996,EB084BDC2C97AFF3,classic_bike,2026-08-10 10:53:03.898,2026-08-10 11:29:31.650,N 12 St & Bedford Ave,5450.04,Van Brunt St & Van Dyke St,4095.10,40.720798,-73.954847,40.675833,-74.014726,member
999997,7FEEC61FAC39EE35,electric_bike,2026-08-12 10:13:53.970,2026-08-12 10:20:54.036,W 52 St & 11 Ave,6926.01,W 47 St & 9 Ave,6786.02,40.767272,-73.993929,40.761530,-73.990070,member
999998,C5A683CC3D7150B0,electric_bike,2026-08-10 10:47:19.134,2026-08-10 10:53:43.795,7 Ave S & Bleecker St,5805.07,Laight St & Hudson St,5539.06,40.732139,-74.003638,40.721854,-74.007718,member
999999,F7D554008276A434,electric_bike,2026-08-05 13:49:47.463,2026-08-05 13:59:02.878,7 Ave S & Bleecker St,5805.07,Laight St & Hudson St,5539.06,40.732139,-74.003638,40.721854,-74.007718,member

In [5]:
df3=pd.read_csv(r"C:\City Bike\data\raw\202608-citibike-tripdata_3.csv")
df3

C:\Users\Chinmaya Harekrishna\AppData\Local\Temp\ipykernel_22152\2575540273.py:1: DtypeWarning: Columns (0: end_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df3=pd.read_csv(r"C:\City Bike\data\raw\202608-citibike-tripdata_3.csv")

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,8DE28BB8DE7E7B37,classic_bike,2026-08-08 13:09:07.617,2026-08-08 13:56:43.819,7 Ave S & Bleecker St,5805.07,Murray St & West St (NW Corner),5329.09,40.732139,-74.003638,40.715438,-74.014077,casual
1,26D1DFF0A7C10B8E,classic_bike,2026-08-06 08:18:45.376,2026-08-06 08:44:50.952,Ave C & McDonald Ave,2957.08,West Drive & Prospect Park West,3651.04,40.640344,-73.979152,40.661063,-73.979453,member
2,D3C1E6BE59C03672,classic_bike,2026-08-04 08:13:55.475,2026-08-04 08:41:50.638,Ave C & McDonald Ave,2957.08,West Drive & Prospect Park West,3651.04,40.640344,-73.979152,40.661063,-73.979453,member
3,896AB31C4062E923,electric_bike,2026-08-06 08:25:17.381,2026-08-06 08:44:10.849,W 52 St & 11 Ave,6926.01,Murray St & West St (NW Corner),5329.09,40.767272,-73.993929,40.715438,-74.014077,member
4,0D9343B067B9A8C1,electric_bike,2026-08-01 18:50:22.934,2026-08-01 18:54:29.064,Hancock St & Malcolm X Blvd,4342.04,Halsey St & Tompkins Ave,4319.07,40.684870,-73.929300,40.682369,-73.944118,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,60D4C98548B9AD05,electric_bike,2026-08-18 09:41:00.056,2026-08-18 10:08:39.527,Grand Ave & W Fordham Rd,8571.02,E 182 St & Grand Concourse,8494.07,40.862880,-73.903160,40.855910,-73.900510,member
999996,B09E12D4908CCBA8,classic_bike,2026-08-24 05:42:09.563,2026-08-24 05:46:14.180,5 Ave & E 30 St,6248.08,W 36 St & 7 Ave,6483.06,40.745985,-73.986295,40.752149,-73.989539,member
999997,EDB190CC044419C4,electric_bike,2026-08-16 01:24:54.216,2026-08-16 01:30:32.323,25 Ave & 41 St,6943.07,24 Ave & 26 St,7152.10,40.767666,-73.910963,40.774591,-73.918544,member
999998,483C962E21C61F35,electric_bike,2026-08-17 23:34:45.472,2026-08-17 23:40:49.561,W 34 St & Hudson Blvd E,6535.04,W 36 St & 7 Ave,6483.06,40.755167,-74.000599,40.752149,-73.989539,member
999999,25DC3F883F354854,electric_bike,2026-08-26 05:48:38.439,2026-08-26 05:56:56.491,E 115 St & Lexington Ave,7599.09,Lenox Ave & W 144 St,7910.01,40.797911,-73.942300,40.819783,-73.936521,member

In [6]:
df4=pd.read_csv(r"C:\City Bike\data\raw\202608-citibike-tripdata_4.csv")
df4

C:\Users\Chinmaya Harekrishna\AppData\Local\Temp\ipykernel_22152\424896728.py:1: DtypeWarning: Columns (0: end_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df4=pd.read_csv(r"C:\City Bike\data\raw\202608-citibike-tripdata_4.csv")

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,84E2F0D9DFC4B3EF,electric_bike,2026-08-22 21:28:45.513,2026-08-22 21:42:28.510,Lenox Ave & W 146 St,7910.10,W 144 St & Adam Clayton Powell Blvd,7932.10,40.821111,-73.935971,40.820877,-73.939249,member
1,BFD3460415548517,classic_bike,2026-08-24 17:58:58.818,2026-08-24 18:40:47.398,8 Ave & W 52 St,6816.07,W 36 St & 7 Ave,6483.06,40.763707,-73.985162,40.752149,-73.989539,member
2,70AA9379134386B9,classic_bike,2026-08-21 18:34:56.213,2026-08-21 18:39:46.751,W 42 St & 6 Ave,6517.08,W 36 St & 7 Ave,6483.06,40.754920,-73.984550,40.752149,-73.989539,member
3,A5585722BC2ABE0E,classic_bike,2026-08-23 17:02:16.867,2026-08-23 17:05:27.168,W 42 St & 6 Ave,6517.08,W 36 St & 7 Ave,6483.06,40.754920,-73.984550,40.752149,-73.989539,member
4,45681799D3A8D79A,classic_bike,2026-08-22 00:57:18.511,2026-08-22 01:08:27.794,8 Ave & W 52 St,6816.07,W 36 St & 7 Ave,6483.06,40.763707,-73.985162,40.752149,-73.989539,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,630ECEB904D4F046,electric_bike,2026-08-25 17:57:36.077,2026-08-25 18:00:17.225,W 11 St & 6 Ave,5914.03,Carmine St & 6 Ave,5763.03,40.735324,-73.998004,40.730386,-74.002150,member
999996,288762FCDD7AE514,classic_bike,2026-08-26 19:47:47.059,2026-08-26 19:55:34.038,W 20 St & 7 Ave,6182.02,Carmine St & 6 Ave,5763.03,40.742388,-73.997262,40.730386,-74.002150,member
999997,E6C602E95050E81C,classic_bike,2026-08-17 18:03:08.318,2026-08-17 18:34:27.520,Columbia St & Rivington St,5365.02,Ave D & E 3 St,5436.09,40.717400,-73.980166,40.720828,-73.977932,member
999998,2A32D3452EEEA630,electric_bike,2026-08-23 22:41:47.437,2026-08-23 22:52:22.531,E 33 St & 1 Ave,6197.08,W 30 St & 10 Ave,6459.07,40.743227,-73.974498,40.752694,-74.002353,member
999999,A782B0BB65674006,electric_bike,2026-08-18 18:07:18.454,2026-08-18 18:22:03.371,W 20 St & 7 Ave,6182.02,River Ter & Warren St,5368.03,40.742388,-73.997262,40.717599,-74.015880,member

In [7]:
df5=pd.read_csv(r"C:\City Bike\data\raw\202608-citibike-tripdata_5.csv")
df5

C:\Users\Chinmaya Harekrishna\AppData\Local\Temp\ipykernel_22152\3287697530.py:1: DtypeWarning: Columns (0: end_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df5=pd.read_csv(r"C:\City Bike\data\raw\202608-citibike-tripdata_5.csv")

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C4CECF5C737BA64C,electric_bike,2026-08-15 08:48:12.512,2026-08-15 09:01:23.497,Walton Ave & E 171 St,8249.10,W 160 St & St Nicholas Ave,8138.07,40.840683,-73.915073,40.834468,-73.939865,member
1,92C6BB64FA8FDE6A,electric_bike,2026-08-19 18:49:17.680,2026-08-19 18:56:24.848,W 20 St & 7 Ave,6182.02,Carmine St & 6 Ave,5763.03,40.742388,-73.997262,40.730386,-74.002150,member
2,BBE2A737B5F01F13,classic_bike,2026-08-25 09:18:26.026,2026-08-25 09:44:44.293,8 Ave & W 55 St,6884.06,River Ter & Warren St,5368.03,40.765591,-73.983846,40.717599,-74.015880,member
3,C9BD598ED4DCCAC0,electric_bike,2026-08-25 07:58:38.251,2026-08-25 08:28:44.306,Wyckoff St & 3 Ave,4290.06,W 30 St & 10 Ave,6459.07,40.682755,-73.982586,40.752694,-74.002353,member
4,53744426CE9CE733,electric_bike,2026-08-21 18:14:21.359,2026-08-21 18:40:38.157,8 Ave & W 55 St,6884.06,Ave D & E 3 St,5436.09,40.765591,-73.983846,40.720828,-73.977932,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,B2F637A4113B03AC,classic_bike,2026-08-29 19:31:07.387,2026-08-29 19:32:11.047,Metropolitan Ave & 65 Ln,5160.01,Metropolitan Ave & 65 Ln,5160.01,40.712250,-73.891110,40.712250,-73.891110,member
999996,3514DB7BA9C7D8FC,classic_bike,2026-08-30 14:59:40.529,2026-08-30 15:19:53.911,Greenwich St & Christopher St,5847.10,Greenwich St & Christopher St,5847.10,40.732600,-74.007670,40.732600,-74.007670,member
999997,79FDF94DEDD24D9A,electric_bike,2026-08-29 09:56:32.991,2026-08-29 10:02:52.763,Kent Ave & N 3 St,5348.06,Kent Ave & N 3 St,5348.06,40.717979,-73.964274,40.717979,-73.964274,member
999998,7BA991F2121B7EFF,electric_bike,2026-08-31 08:30:54.062,2026-08-31 08:37:20.787,6 Ave & Walker St,5430.10,Greenwich St & Christopher St,5847.10,40.719792,-74.005224,40.732600,-74.007670,member
999999,7BBD2C6D9DAF7AA6,electric_bike,2026-08-31 07:13:48.366,2026-08-31 07:18:35.810,Greenwich St & Christopher St,5847.10,6 Ave & Walker St,5430.10,40.732600,-74.007670,40.719792,-74.005224,member

In [8]:
import pandas as pd
df6=pd.read_csv(r"C:\City Bike\data\raw\202608-citibike-tripdata_6.csv")
df6

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,68A2FD2BC7E2DB2D,electric_bike,2026-08-29 23:28:26.468,2026-08-29 23:29:43.206,11 Ave & W 27 St,6425.04,11 Ave & W 27 St,6425.04,40.751396,-74.005226,40.751396,-74.005226,member
1,739523CE755DE11A,electric_bike,2026-08-29 13:43:26.482,2026-08-29 13:58:43.048,6 Ave & Walker St,5430.10,11 Ave & W 27 St,6425.04,40.719792,-74.005224,40.751396,-74.005226,member
2,3A533A67141355B3,electric_bike,2026-08-31 12:46:12.602,2026-08-31 12:52:27.078,Linden Blvd & Nostrand Ave,3359.03,Parkside Ave & Ocean Ave,3448.02,40.652720,-73.949940,40.654850,-73.962170,member
3,B07D82B060FF337C,electric_bike,2026-08-30 18:29:34.914,2026-08-30 18:31:55.640,E 72 St & York Ave,6889.12,E 72 St & York Ave,6889.12,40.766638,-73.953483,40.766638,-73.953483,member
4,C603C3B788201E51,electric_bike,2026-08-30 21:41:30.283,2026-08-30 22:00:25.298,Sterling Pl & Classon Ave,4033.18,Sterling Pl & Classon Ave,4033.18,40.673941,-73.960260,40.673941,-73.960260,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
246231,7778C182C86ED253,electric_bike,2026-08-29 16:40:59.109,2026-08-29 16:52:10.441,Caton Ave & Argyle Rd,3303.03,West Drive & Prospect Park West,3651.04,40.649681,-73.967829,40.661063,-73.979453,member
246232,7E1978AE88707549,electric_bike,2026-08-30 14:40:57.513,2026-08-30 14:45:19.773,Lexington Ave & E 26 St,6089.08,E 39 St & Lexington Ave,6389.09,40.741459,-73.983293,40.749499,-73.977292,member
246233,EE79B9E27476A26B,electric_bike,2026-08-29 17:44:45.322,2026-08-29 18:18:35.303,Kent Ave & N 7 St,5489.03,West Drive & Prospect Park West,3651.04,40.720368,-73.961651,40.661063,-73.979453,member
246234,2C83FD498727AFDD,electric_bike,2026-08-31 17:26:01.392,2026-08-31 17:36:15.940,E 31 St & 3 Ave,6239.08,W 39 St & 9 Ave,6644.04,40.743943,-73.979661,40.756458,-73.993722,casual
246235,A0A5A6D9CB904049,electric_bike,2026-08-30 15:43:45.477,2026-08-30 16:18:26.236,Lawrence St & Willoughby St,4596.09,Van Brunt St & Van Dyke St,4095.10,40.692362,-73.986317,40.675833,-74.014726,casual

In [9]:
df_all = pd.concat([df1, df2, df3, df4, df5, df6], ignore_index=True)

df_all

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,40.744876,-73.995299,member
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,40.744876,-73.995299,member
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,40.744876,-73.995299,member
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5246231,7778C182C86ED253,electric_bike,2026-08-29 16:40:59.109,2026-08-29 16:52:10.441,Caton Ave & Argyle Rd,3303.03,West Drive & Prospect Park West,3651.04,40.649681,-73.967829,40.661063,-73.979453,member
5246232,7E1978AE88707549,electric_bike,2026-08-30 14:40:57.513,2026-08-30 14:45:19.773,Lexington Ave & E 26 St,6089.08,E 39 St & Lexington Ave,6389.09,40.741459,-73.983293,40.749499,-73.977292,member
5246233,EE79B9E27476A26B,electric_bike,2026-08-29 17:44:45.322,2026-08-29 18:18:35.303,Kent Ave & N 7 St,5489.03,West Drive & Prospect Park West,3651.04,40.720368,-73.961651,40.661063,-73.979453,member
5246234,2C83FD498727AFDD,electric_bike,2026-08-31 17:26:01.392,2026-08-31 17:36:15.940,E 31 St & 3 Ave,6239.08,W 39 St & 9 Ave,6644.04,40.743943,-73.979661,40.756458,-73.993722,casual
5246235,A0A5A6D9CB904049,electric_bike,2026-08-30 15:43:45.477,2026-08-30 16:18:26.236,Lawrence St & Willoughby St,4596.09,Van Brunt St & Van Dyke St,4095.10,40.692362,-73.986317,40.675833,-74.014726,casual

In [10]:
df_all.shape

(5246236, 13)

In [11]:
df_all.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')

In [12]:
df_all.isnull().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name     2870
start_station_id       2870
end_station_name      13792
end_station_id        14767
start_lat              2870
start_lng              2870
end_lat               14733
end_lng               14733
member_casual             0
dtype: int64

In [13]:
df_all.duplicated().sum()

np.int64(0)

In [14]:
df_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 5246236 entries, 0 to 5246235
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             str
 1   rideable_type       str
 2   started_at          str
 3   ended_at            str
 4   start_station_name  str
 5   start_station_id    str
 6   end_station_name    str
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       str
dtypes: float64(4), object(1), str(8)
memory usage: 520.3+ MB

In [15]:
df_all.duplicated().sum()

np.int64(0)

In [16]:
df_all['rideable_type'].value_counts()

rideable_type
electric_bike    3832654
classic_bike     1413582
Name: count, dtype: int64

In [17]:
len(df_all["ride_id"])

5246236

In [18]:
3832654+1413582

5246236

In [19]:
len(df_all[df_all['rideable_type']=="classic_bike"])

1413582

In [20]:
len(df_all[df_all['rideable_type']=="electric_bike"])

3832654

In [21]:
df_all.isnull().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name     2870
start_station_id       2870
end_station_name      13792
end_station_id        14767
start_lat              2870
start_lng              2870
end_lat               14733
end_lng               14733
member_casual             0
dtype: int64

In [22]:
df_all['start_station_name'].mode()[0]

'W 21 St & 6 Ave'

In [23]:
df_all['start_station_name'] = df_all['start_station_name'].fillna(df_all['start_station_name'].mode()[0])
df_all.isnull().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name        0
start_station_id       2870
end_station_name      13792
end_station_id        14767
start_lat              2870
start_lng              2870
end_lat               14733
end_lng               14733
member_casual             0
dtype: int64

In [24]:
df_all['start_station_id'] = df_all['start_station_id'].fillna(df_all['start_station_id'].mode()[0])
df_all['end_station_name'] = df_all['end_station_name'].fillna(df_all['end_station_name'].mode()[0])
df_all['end_station_id'] = df_all['end_station_id'].fillna(df_all['end_station_id'].mode()[0])
df_all['start_lat'] = df_all['start_lat'].fillna(df_all['start_lat'].mean())
df_all['start_lng'] = df_all['start_lng'].fillna(df_all['start_lng'].mean())
df_all['end_lat'] = df_all['end_lat'].fillna(df_all['end_lat'].mean())
df_all['end_lng'] = df_all['end_lng'].fillna(df_all['end_lng'].mean())

In [25]:
df_all["started_at"] = pd.to_datetime(df_all["started_at"], errors="coerce")
df_all["ended_at"] = pd.to_datetime(df_all["ended_at"], errors="coerce")

df_all[["started_at", "ended_at"]].head()

               started_at                ended_at
0 2026-08-10 14:31:22.100 2026-08-10 14:37:37.034
1 2026-08-10 08:04:28.348 2026-08-10 08:33:27.680
2 2026-08-08 19:36:32.350 2026-08-08 19:43:47.890
3 2026-08-05 14:34:27.749 2026-08-05 14:46:23.526
4 2026-08-01 14:16:44.531 2026-08-01 14:29:39.539

In [26]:
df_all[["started_at", "ended_at"]].isna().sum()

started_at    0
ended_at      0
dtype: int64

In [27]:
df_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 5246236 entries, 0 to 5246235
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             str
 1   rideable_type       str
 2   started_at          datetime64[us]
 3   ended_at            datetime64[us]
 4   start_station_name  str
 5   start_station_id    str
 6   end_station_name    str
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       str
dtypes: datetime64[us](2), float64(4), object(1), str(6)
memory usage: 520.3+ MB

In [28]:
df_all["started_at"] = pd.to_datetime(df_all["started_at"], errors="coerce")
df_all["ended_at"] = pd.to_datetime(df_all["ended_at"], errors="coerce")

df_all["trip_duration_min"] = (
    df_all["ended_at"] - df_all["started_at"]
).dt.total_seconds() / 60

df_all[["started_at", "ended_at", "trip_duration_min"]].head()

               started_at                ended_at  trip_duration_min
0 2026-08-10 14:31:22.100 2026-08-10 14:37:37.034           6.248900
1 2026-08-10 08:04:28.348 2026-08-10 08:33:27.680          28.988867
2 2026-08-08 19:36:32.350 2026-08-08 19:43:47.890           7.259000
3 2026-08-05 14:34:27.749 2026-08-05 14:46:23.526          11.929617
4 2026-08-01 14:16:44.531 2026-08-01 14:29:39.539          12.916800

In [30]:
df_all = df_all[
    (df_all["trip_duration_min"] > 1) &
    (df_all["trip_duration_min"] < 24 * 60)
].copy()

df_all = df_all.reset_index(drop=True)

df_all

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,trip_duration_min
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,40.744876,-73.995299,member,6.248900
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,40.744876,-73.995299,member,28.988867
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,40.744876,-73.995299,member,7.259000
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member,11.929617
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member,12.916800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5244968,7778C182C86ED253,electric_bike,2026-08-29 16:40:59.109,2026-08-29 16:52:10.441,Caton Ave & Argyle Rd,3303.03,West Drive & Prospect Park West,3651.04,40.649681,-73.967829,40.661063,-73.979453,member,11.188867
5244969,7E1978AE88707549,electric_bike,2026-08-30 14:40:57.513,2026-08-30 14:45:19.773,Lexington Ave & E 26 St,6089.08,E 39 St & Lexington Ave,6389.09,40.741459,-73.983293,40.749499,-73.977292,member,4.371000
5244970,EE79B9E27476A26B,electric_bike,2026-08-29 17:44:45.322,2026-08-29 18:18:35.303,Kent Ave & N 7 St,5489.03,West Drive & Prospect Park West,3651.04,40.720368,-73.961651,40.661063,-73.979453,member,33.833017
5244971,2C83FD498727AFDD,electric_bike,2026-08-31 17:26:01.392,2026-08-31 17:36:15.940,E 31 St & 3 Ave,6239.08,W 39 St & 9 Ave,6644.04,40.743943,-73.979661,40.756458,-73.993722,casual,10.242467
5244972,A0A5A6D9CB904049,electric_bike,2026-08-30 15:43:45.477,2026-08-30 16:18:26.236,Lawrence St & Willoughby St,4596.09,Van Brunt St & Van Dyke St,4095.10,40.692362,-73.986317,40.675833,-74.014726,casual,34.679317

In [31]:
df_all = df_all.drop_duplicates(subset=["ride_id"]).copy()

df_all = df_all.reset_index(drop=True)

In [33]:
print("After cleaning trips:", df_all.shape)

After cleaning trips: (5244973, 14)

In [34]:
df_all.isnull().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
trip_duration_min     0
dtype: int64

In [35]:
df_all.dtypes

ride_id                          str
rideable_type                    str
started_at            datetime64[us]
ended_at              datetime64[us]
start_station_name               str
start_station_id                 str
end_station_name                 str
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                    str
trip_duration_min            float64
dtype: object

In [36]:
df_all

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,trip_duration_min
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,40.744876,-73.995299,member,6.248900
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,40.744876,-73.995299,member,28.988867
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,40.744876,-73.995299,member,7.259000
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member,11.929617
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member,12.916800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5244968,7778C182C86ED253,electric_bike,2026-08-29 16:40:59.109,2026-08-29 16:52:10.441,Caton Ave & Argyle Rd,3303.03,West Drive & Prospect Park West,3651.04,40.649681,-73.967829,40.661063,-73.979453,member,11.188867
5244969,7E1978AE88707549,electric_bike,2026-08-30 14:40:57.513,2026-08-30 14:45:19.773,Lexington Ave & E 26 St,6089.08,E 39 St & Lexington Ave,6389.09,40.741459,-73.983293,40.749499,-73.977292,member,4.371000
5244970,EE79B9E27476A26B,electric_bike,2026-08-29 17:44:45.322,2026-08-29 18:18:35.303,Kent Ave & N 7 St,5489.03,West Drive & Prospect Park West,3651.04,40.720368,-73.961651,40.661063,-73.979453,member,33.833017
5244971,2C83FD498727AFDD,electric_bike,2026-08-31 17:26:01.392,2026-08-31 17:36:15.940,E 31 St & 3 Ave,6239.08,W 39 St & 9 Ave,6644.04,40.743943,-73.979661,40.756458,-73.993722,casual,10.242467
5244972,A0A5A6D9CB904049,electric_bike,2026-08-30 15:43:45.477,2026-08-30 16:18:26.236,Lawrence St & Willoughby St,4596.09,Van Brunt St & Van Dyke St,4095.10,40.692362,-73.986317,40.675833,-74.014726,casual,34.679317

In [37]:
df_all.isnull().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
trip_duration_min     0
dtype: int64

In [38]:
df_all['start_station_name'].value_counts()

start_station_name
W 21 St & 6 Ave                    20597
Pier 61 at Chelsea Piers           16752
E 17 St & Broadway                 16044
7 Ave & Central Park South         15312
W 31 St & 7 Ave                    15189
                                   ...
Barbey St & Fulton St                  9
Van Siclen Ave & Arlington Ave         9
Mother Gaston Blvd & Newport St        8
Shop Morgan                            7
Riverdale Ave & Osborn St              6
Name: count, Length: 2342, dtype: int64

In [39]:
df_all['end_station_name'].value_counts()

end_station_name
W 21 St & 6 Ave                 30331
Pier 61 at Chelsea Piers        16710
E 17 St & Broadway              16152
7 Ave & Central Park South      15081
W 31 St & 7 Ave                 15079
                                ...
4 St & Grand St                     1
Mallory Ave & Roosevelt Ave         1
6 St & Grand St                     1
Hudson Pl & Hoboken Terminal        1
Madison St & 10 St                  1
Name: count, Length: 2393, dtype: int64

In [40]:
df_all['member_casual'].value_counts()

member_casual
member    4117846
casual    1127127
Name: count, dtype: int64

In [41]:
df_all

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,trip_duration_min
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,40.744876,-73.995299,member,6.248900
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,40.744876,-73.995299,member,28.988867
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,40.744876,-73.995299,member,7.259000
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member,11.929617
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member,12.916800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5244968,7778C182C86ED253,electric_bike,2026-08-29 16:40:59.109,2026-08-29 16:52:10.441,Caton Ave & Argyle Rd,3303.03,West Drive & Prospect Park West,3651.04,40.649681,-73.967829,40.661063,-73.979453,member,11.188867
5244969,7E1978AE88707549,electric_bike,2026-08-30 14:40:57.513,2026-08-30 14:45:19.773,Lexington Ave & E 26 St,6089.08,E 39 St & Lexington Ave,6389.09,40.741459,-73.983293,40.749499,-73.977292,member,4.371000
5244970,EE79B9E27476A26B,electric_bike,2026-08-29 17:44:45.322,2026-08-29 18:18:35.303,Kent Ave & N 7 St,5489.03,West Drive & Prospect Park West,3651.04,40.720368,-73.961651,40.661063,-73.979453,member,33.833017
5244971,2C83FD498727AFDD,electric_bike,2026-08-31 17:26:01.392,2026-08-31 17:36:15.940,E 31 St & 3 Ave,6239.08,W 39 St & 9 Ave,6644.04,40.743943,-73.979661,40.756458,-73.993722,casual,10.242467
5244972,A0A5A6D9CB904049,electric_bike,2026-08-30 15:43:45.477,2026-08-30 16:18:26.236,Lawrence St & Willoughby St,4596.09,Van Brunt St & Van Dyke St,4095.10,40.692362,-73.986317,40.675833,-74.014726,casual,34.679317

In [43]:
df_all.duplicated().sum()

np.int64(0)

In [44]:
df_all = df_all.copy()

df_all.columns = df_all.columns.str.strip()
df_all.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'trip_duration_min'],
      dtype='str')

In [43]:
df_all["start_station_name"] = df_all["start_station_name"].fillna(
    df_all["start_station_name"].mode()[0]

)
df_all["start_station_name"]

0                      E 33 St & 5 Ave
1              Emerson Pl & Myrtle Ave
2                   Broadway & E 19 St
3            Sterling Pl & Bedford Ave
4            Sterling Pl & Bedford Ave
                      ...
5246231          Caton Ave & Argyle Rd
5246232        Lexington Ave & E 26 St
5246233              Kent Ave & N 7 St
5246234                E 31 St & 3 Ave
5246235    Lawrence St & Willoughby St
Name: start_station_name, Length: 5246236, dtype: str

In [44]:
df_all["start_station_id "] = df_all["start_station_id"].fillna(
    df_all["start_station_id"].mode()[0]

)
df_all["start_station_id "]

0          6322.01
1          4683.02
2          5980.11
3          3993.03
4          3993.03
            ...
5246231    3303.03
5246232    6089.08
5246233    5489.03
5246234    6239.08
5246235    4596.09
Name: start_station_id , Length: 5246236, dtype: str

In [45]:
df_all["end_station_name "] = df_all["end_station_name"].fillna(
    df_all["end_station_name"].mode()[0]
)
df_all["end_station_name "]

0                          W 24 St & 7 Ave
1                          W 24 St & 7 Ave
2                          W 24 St & 7 Ave
3            Cumberland St & Lafayette Ave
4            Cumberland St & Lafayette Ave
                        ...
5246231    West Drive & Prospect Park West
5246232            E 39 St & Lexington Ave
5246233    West Drive & Prospect Park West
5246234                    W 39 St & 9 Ave
5246235         Van Brunt St & Van Dyke St
Name: end_station_name , Length: 5246236, dtype: str

In [46]:
df_all["end_station_id "] = df_all["end_station_id"].fillna(
    df_all["end_station_id"].mode()[0]
)
df_all["end_station_id "]

0          6257.03
1          6257.03
2          6257.03
3          4428.02
4          4428.02
            ...
5246231    3651.04
5246232    6389.09
5246233    3651.04
5246234    6644.04
5246235    4095.10
Name: end_station_id , Length: 5246236, dtype: object

In [47]:
df_all["start_station_id"] = pd.to_numeric(
    df_all["start_station_id"], errors="coerce"
)

df_all["start_station_id"] = df_all["start_station_id"].fillna(
    df_all["start_station_id"].mean()
).astype(float)

In [48]:
df_all["start_lat"] = df_all["start_lat"].fillna(
    df_all["start_lat"].mean()
)
df_all["start_lat"]

0          40.747659
1          40.693631
2          40.738290
3          40.672695
4          40.672695
             ...
5246231    40.649681
5246232    40.741459
5246233    40.720368
5246234    40.743943
5246235    40.692362
Name: start_lat, Length: 5246236, dtype: float64

In [49]:
df_all["start_lng"] = df_all["start_lng"].fillna(
    df_all["start_lng"].mean())
df_all["start_lng"]

0         -73.984907
1         -73.962236
2         -73.990060
3         -73.954131
4         -73.954131
             ...
5246231   -73.967829
5246232   -73.983293
5246233   -73.961651
5246234   -73.979661
5246235   -73.986317
Name: start_lng, Length: 5246236, dtype: float64

In [50]:
df_all["end_lat"] = df_all["end_lat"].fillna(
    df_all["end_lat"].mean())
df_all["end_lat"]

0          40.744876
1          40.744876
2          40.744876
3          40.687534
4          40.687534
             ...
5246231    40.661063
5246232    40.749499
5246233    40.661063
5246234    40.756458
5246235    40.675833
Name: end_lat, Length: 5246236, dtype: float64

In [51]:
df_all["end_lng"] = df_all["end_lng"].fillna(
    df_all["end_lng"].mean())
df_all["end_lng"]

0         -73.995299
1         -73.995299
2         -73.995299
3         -73.972652
4         -73.972652
             ...
5246231   -73.979453
5246232   -73.977292
5246233   -73.979453
5246234   -73.993722
5246235   -74.014726
Name: end_lng, Length: 5246236, dtype: float64

In [52]:
df_all.isnull().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name        0
start_station_id          0
end_station_name      13792
end_station_id        14767
start_lat                 0
start_lng                 0
end_lat                   0
end_lng                   0
member_casual             0
start_station_id          0
end_station_name          0
end_station_id            0
dtype: int64

In [36]:
df_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 5246236 entries, 0 to 5246235
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             str
 1   rideable_type       str
 2   started_at          str
 3   ended_at            str
 4   start_station_name  str
 5   start_station_id    str
 6   end_station_name    str
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       str
dtypes: float64(4), object(1), str(8)
memory usage: 520.3+ MB

In [54]:
df_all["start_station_id"] = pd.to_numeric(df_all["start_station_id"], errors="coerce")

df_all["start_station_id"] = df_all["start_station_id"].fillna(df_all["start_station_id"].mean())

df_all["start_station_id"]

0          6322.01
1          4683.02
2          5980.11
3          3993.03
4          3993.03
            ...
5246231    3303.03
5246232    6089.08
5246233    5489.03
5246234    6239.08
5246235    4596.09
Name: start_station_id, Length: 5246236, dtype: float64

In [55]:
df_all["end_station_name"] = df_all["end_station_name"].fillna(
    df_all["end_station_name"].mode()[0]
)
df_all["end_station_name"]

0                          W 24 St & 7 Ave
1                          W 24 St & 7 Ave
2                          W 24 St & 7 Ave
3            Cumberland St & Lafayette Ave
4            Cumberland St & Lafayette Ave
                        ...
5246231    West Drive & Prospect Park West
5246232            E 39 St & Lexington Ave
5246233    West Drive & Prospect Park West
5246234                    W 39 St & 9 Ave
5246235         Van Brunt St & Van Dyke St
Name: end_station_name, Length: 5246236, dtype: str

In [56]:
df_all["end_station_id"] = pd.to_numeric(
    df_all["end_station_id"], errors="coerce"
)

df_all["end_station_id"] = df_all["end_station_id"].fillna(
    df_all["end_station_id"].mean()
)

df_all["end_station_id"]

0          6257.03
1          6257.03
2          6257.03
3          4428.02
4          4428.02
            ...
5246231    3651.04
5246232    6389.09
5246233    3651.04
5246234    6644.04
5246235    4095.10
Name: end_station_id, Length: 5246236, dtype: float64

In [57]:
df_all.isnull().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
start_station_id      0
end_station_name      0
end_station_id        0
dtype: int64

In [58]:
df_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 5246236 entries, 0 to 5246235
Data columns (total 16 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             str
 1   rideable_type       str
 2   started_at          str
 3   ended_at            str
 4   start_station_name  str
 5   start_station_id    float64
 6   end_station_name    str
 7   end_station_id      float64
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       str
 13  start_station_id    str
 14  end_station_name    str
 15  end_station_id      object
dtypes: float64(6), object(1), str(9)
memory usage: 640.4+ MB

In [59]:
df_all.isna().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
start_station_id      0
end_station_name      0
end_station_id        0
dtype: int64

In [ ]:
df_all['start_time'] = pd.to_datetime(df_all['started_at'])
df_all['stop_time'] = pd.to_datetime(df_all['ended_at'])

In [45]:
df_all

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,trip_duration_min
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,40.744876,-73.995299,member,6.248900
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,40.744876,-73.995299,member,28.988867
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,40.744876,-73.995299,member,7.259000
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member,11.929617
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member,12.916800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5244968,7778C182C86ED253,electric_bike,2026-08-29 16:40:59.109,2026-08-29 16:52:10.441,Caton Ave & Argyle Rd,3303.03,West Drive & Prospect Park West,3651.04,40.649681,-73.967829,40.661063,-73.979453,member,11.188867
5244969,7E1978AE88707549,electric_bike,2026-08-30 14:40:57.513,2026-08-30 14:45:19.773,Lexington Ave & E 26 St,6089.08,E 39 St & Lexington Ave,6389.09,40.741459,-73.983293,40.749499,-73.977292,member,4.371000
5244970,EE79B9E27476A26B,electric_bike,2026-08-29 17:44:45.322,2026-08-29 18:18:35.303,Kent Ave & N 7 St,5489.03,West Drive & Prospect Park West,3651.04,40.720368,-73.961651,40.661063,-73.979453,member,33.833017
5244971,2C83FD498727AFDD,electric_bike,2026-08-31 17:26:01.392,2026-08-31 17:36:15.940,E 31 St & 3 Ave,6239.08,W 39 St & 9 Ave,6644.04,40.743943,-73.979661,40.756458,-73.993722,casual,10.242467
5244972,A0A5A6D9CB904049,electric_bike,2026-08-30 15:43:45.477,2026-08-30 16:18:26.236,Lawrence St & Willoughby St,4596.09,Van Brunt St & Van Dyke St,4095.10,40.692362,-73.986317,40.675833,-74.014726,casual,34.679317

In [63]:
df_all['Trip_Duration'] = (df_all['stop_time'] - df_all['start_time'])
df_all

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_station_id,end_station_name,end_station_id,start_time,stop_time,Trip_Duration
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,40.744876,-73.995299,member,6322.01,W 24 St & 7 Ave,6257.03,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,0 days 00:06:14.934000
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,40.744876,-73.995299,member,4683.02,W 24 St & 7 Ave,6257.03,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,0 days 00:28:59.332000
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,40.744876,-73.995299,member,5980.11,W 24 St & 7 Ave,6257.03,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,0 days 00:07:15.540000
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member,3993.03,Cumberland St & Lafayette Ave,4428.02,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,0 days 00:11:55.777000
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,40.687534,-73.972652,member,3993.03,Cumberland St & Lafayette Ave,4428.02,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,0 days 00:12:55.008000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5246231,7778C182C86ED253,electric_bike,2026-08-29 16:40:59.109,2026-08-29 16:52:10.441,Caton Ave & Argyle Rd,3303.03,West Drive & Prospect Park West,3651.04,40.649681,-73.967829,40.661063,-73.979453,member,3303.03,West Drive & Prospect Park West,3651.04,2026-08-29 16:40:59.109,2026-08-29 16:52:10.441,0 days 00:11:11.332000
5246232,7E1978AE88707549,electric_bike,2026-08-30 14:40:57.513,2026-08-30 14:45:19.773,Lexington Ave & E 26 St,6089.08,E 39 St & Lexington Ave,6389.09,40.741459,-73.983293,40.749499,-73.977292,member,6089.08,E 39 St & Lexington Ave,6389.09,2026-08-30 14:40:57.513,2026-08-30 14:45:19.773,0 days 00:04:22.260000
5246233,EE79B9E27476A26B,electric_bike,2026-08-29 17:44:45.322,2026-08-29 18:18:35.303,Kent Ave & N 7 St,5489.03,West Drive & Prospect Park West,3651.04,40.720368,-73.961651,40.661063,-73.979453,member,5489.03,West Drive & Prospect Park West,3651.04,2026-08-29 17:44:45.322,2026-08-29 18:18:35.303,0 days 00:33:49.981000
5246234,2C83FD498727AFDD,electric_bike,2026-08-31 17:26:01.392,2026-08-31 17:36:15.940,E 31 St & 3 Ave,6239.08,W 39 St & 9 Ave,6644.04,40.743943,-73.979661,40.756458,-73.993722,casual,6239.08,W 39 St & 9 Ave,6644.04,2026-08-31 17:26:01.392,2026-08-31 17:36:15.940,0 days 00:10:14.548000
5246235,A0A5A6D9CB904049,electric_bike,2026-08-30 15:43:45.477,2026-08-30 16:18:26.236,Lawrence St & Willoughby St,4596.09,Van Brunt St & Van Dyke St,4095.10,40.692362,-73.986317,40.675833,-74.014726,casual,4596.09,Van Brunt St & Van Dyke St,4095.10,2026-08-30 15:43:45.477,2026-08-30 16:18:26.236,0 days 00:34:40.759000

In [47]:
df_all.to_csv(
    r"C:\City Bike\data\processed\citibike_cleaned.csv",
    index=False
)

print("Saved:", r"C:\City Bike\data\processed\citibike_cleaned.csv")

Saved: C:\City Bike\data\processed\citibike_cleaned.csv

In [48]:
df.head()

,station_id,name,short_name,lon,lat,region_id,capacity,rental_uris,rental_methods,has_kiosk,station_type,external_id,electric_bike_surcharge_waiver,eightd_station_services,eightd_has_key_dispenser
0,2250953816197165238,New Lots Ave & Van Sinderen Ave,3565.07,-73.899150,40.659230,71.0,16,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",False,classic,2250953816197165238,False,[],False
1,18eccc71-66be-4e4c-8335-095a9bf0df94,Adam Clayton Powell Blvd & W 126 St,7738.04,-73.947765,40.809495,71.0,33,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,18eccc71-66be-4e4c-8335-095a9bf0df94,False,[],False
2,1822663031356509142,Matthews Ct & Coney Island Ave,3034.02,-73.969510,40.642350,71.0,0,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,1822663031356509142,False,[],False
3,7a6fc75f-a605-4dd6-b567-b2bbbfb862f3,65 Pl & 53 Ave,5764.02,-73.900220,40.731450,71.0,19,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,7a6fc75f-a605-4dd6-b567-b2bbbfb862f3,False,[],False
4,2235294222661977076,Livonia Ave & Powell St,3678.05,-73.902310,40.663630,71.0,0,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",False,classic,2235294222661977076,False,[],False

In [49]:
df=pd.read_csv(r"C:\City Bike\data\external\station_information.csv")
df

,station_id,name,short_name,lon,lat,region_id,capacity,rental_uris,rental_methods,has_kiosk,station_type,external_id,electric_bike_surcharge_waiver,eightd_station_services,eightd_has_key_dispenser
0,2250953816197165238,New Lots Ave & Van Sinderen Ave,3565.07,-73.899150,40.659230,71.0,16,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",False,classic,2250953816197165238,False,[],False
1,18eccc71-66be-4e4c-8335-095a9bf0df94,Adam Clayton Powell Blvd & W 126 St,7738.04,-73.947765,40.809495,71.0,33,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,18eccc71-66be-4e4c-8335-095a9bf0df94,False,[],False
2,1822663031356509142,Matthews Ct & Coney Island Ave,3034.02,-73.969510,40.642350,71.0,0,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,1822663031356509142,False,[],False
3,7a6fc75f-a605-4dd6-b567-b2bbbfb862f3,65 Pl & 53 Ave,5764.02,-73.900220,40.731450,71.0,19,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,7a6fc75f-a605-4dd6-b567-b2bbbfb862f3,False,[],False
4,2235294222661977076,Livonia Ave & Powell St,3678.05,-73.902310,40.663630,71.0,0,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",False,classic,2235294222661977076,False,[],False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2515,66ddd93e-0aca-11e7-82f6-3863bb44ef7c,Jersey & 6th St,JC027,-74.045572,40.725289,70.0,14,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,66ddd93e-0aca-11e7-82f6-3863bb44ef7c,False,[],False
2516,9d344652-976b-4c2d-bede-2ef19b0fbf13,6 St & Grand St,HB302,-74.034501,40.744398,311.0,18,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,9d344652-976b-4c2d-bede-2ef19b0fbf13,False,[],False
2517,519824e4-69ba-4270-a395-17c204f328f8,8 St & Washington St,HB603,-74.028199,40.745984,311.0,21,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,519824e4-69ba-4270-a395-17c204f328f8,False,[],False
2518,66ddd8a8-0aca-11e7-82f6-3863bb44ef7c,Brunswick & 6th,JC081,-74.050389,40.726012,70.0,14,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,66ddd8a8-0aca-11e7-82f6-3863bb44ef7c,False,[],False
2519,66ddddb4-0aca-11e7-82f6-3863bb44ef7c,Monmouth & 6th,JC075,-74.048790,40.725685,70.0,14,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,66ddddb4-0aca-11e7-82f6-3863bb44ef7c,False,[],False

In [50]:
df.isnull().sum()

station_id                         0
name                               0
short_name                         0
lon                                0
lat                                0
region_id                         13
capacity                           0
rental_uris                        0
rental_methods                     0
has_kiosk                          0
station_type                       0
external_id                        0
electric_bike_surcharge_waiver     0
eightd_station_services            0
eightd_has_key_dispenser           0
dtype: int64

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2520 entries, 0 to 2519
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   station_id                      2520 non-null   str
 1   name                            2520 non-null   str
 2   short_name                      2520 non-null   str
 3   lon                             2520 non-null   float64
 4   lat                             2520 non-null   float64
 5   region_id                       2507 non-null   float64
 6   capacity                        2520 non-null   int64
 7   rental_uris                     2520 non-null   str
 8   rental_methods                  2520 non-null   str
 9   has_kiosk                       2520 non-null   bool
 10  station_type                    2520 non-null   str
 11  external_id                     2520 non-null   str
 12  electric_bike_surcharge_waiver  2520 non-null   bool
 13  eightd_station_services         2520 non-null   str
 14  eightd_has_key_dispenser        2520 non-null   bool
dtypes: bool(3), float64(3), int64(1), str(8)
memory usage: 243.8 KB

In [52]:
df_all = df.copy()
df_all['region_id'] = df_all['region_id'].fillna(df_all['region_id'].mean())
df_all['region_id']

0        71.0
1        71.0
2        71.0
3        71.0
4        71.0
        ...
2515     70.0
2516    311.0
2517    311.0
2518     70.0
2519     70.0
Name: region_id, Length: 2520, dtype: float64

In [53]:
df.copy()
stations =['station_id', 'name', 'lat', 'lon', 'capacity']

In [54]:
df = df.rename(columns={
    'name': 'station_name',
    'lat': 'latitude',
    'lon': 'longitude'
})
df

,station_id,station_name,short_name,longitude,latitude,region_id,capacity,rental_uris,rental_methods,has_kiosk,station_type,external_id,electric_bike_surcharge_waiver,eightd_station_services,eightd_has_key_dispenser
0,2250953816197165238,New Lots Ave & Van Sinderen Ave,3565.07,-73.899150,40.659230,71.0,16,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",False,classic,2250953816197165238,False,[],False
1,18eccc71-66be-4e4c-8335-095a9bf0df94,Adam Clayton Powell Blvd & W 126 St,7738.04,-73.947765,40.809495,71.0,33,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,18eccc71-66be-4e4c-8335-095a9bf0df94,False,[],False
2,1822663031356509142,Matthews Ct & Coney Island Ave,3034.02,-73.969510,40.642350,71.0,0,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,1822663031356509142,False,[],False
3,7a6fc75f-a605-4dd6-b567-b2bbbfb862f3,65 Pl & 53 Ave,5764.02,-73.900220,40.731450,71.0,19,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,7a6fc75f-a605-4dd6-b567-b2bbbfb862f3,False,[],False
4,2235294222661977076,Livonia Ave & Powell St,3678.05,-73.902310,40.663630,71.0,0,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",False,classic,2235294222661977076,False,[],False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2515,66ddd93e-0aca-11e7-82f6-3863bb44ef7c,Jersey & 6th St,JC027,-74.045572,40.725289,70.0,14,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,66ddd93e-0aca-11e7-82f6-3863bb44ef7c,False,[],False
2516,9d344652-976b-4c2d-bede-2ef19b0fbf13,6 St & Grand St,HB302,-74.034501,40.744398,311.0,18,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,9d344652-976b-4c2d-bede-2ef19b0fbf13,False,[],False
2517,519824e4-69ba-4270-a395-17c204f328f8,8 St & Washington St,HB603,-74.028199,40.745984,311.0,21,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,519824e4-69ba-4270-a395-17c204f328f8,False,[],False
2518,66ddd8a8-0aca-11e7-82f6-3863bb44ef7c,Brunswick & 6th,JC081,-74.050389,40.726012,70.0,14,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,66ddd8a8-0aca-11e7-82f6-3863bb44ef7c,False,[],False
2519,66ddddb4-0aca-11e7-82f6-3863bb44ef7c,Monmouth & 6th,JC075,-74.048790,40.725685,70.0,14,{'android': 'https://bkn.lft.to/lastmile_qr_sc...,"['KEY', 'CREDITCARD']",True,classic,66ddddb4-0aca-11e7-82f6-3863bb44ef7c,False,[],False

In [55]:
df_all.isnull().sum()

station_id                        0
name                              0
short_name                        0
lon                               0
lat                               0
region_id                         0
capacity                          0
rental_uris                       0
rental_methods                    0
has_kiosk                         0
station_type                      0
external_id                       0
electric_bike_surcharge_waiver    0
eightd_station_services           0
eightd_has_key_dispenser          0
dtype: int64

In [56]:
df.to_csv('cleaned_data.csv', index=False)

In [57]:
# import pandas as pd

# df1 = pd.read_csv(r"C:\City Bike\data\processed\citibike_combined.csv")
# df2 = pd.read_csv(r"C:\City Bike\notebooks\cleaned_data.csv")

# # Keep common columns
# common_columns = df1.columns.intersection(df2.columns)

# df1 = df1[common_columns]
# df2 = df2[common_columns]

# # Concatenate
# merged = pd.concat([df1, df2], ignore_index=True)

# # Fill missing values
# for col in merged.columns:
#     if merged[col].dtype == "object":
#         merged[col] = merged[col].fillna("Unknown")
#     else:
#         merged[col] = merged[col].fillna(0)

# # Check NaN
# print(merged.isna().sum().sum())

# merged







import pandas as pd

# Load cleaned trip data
trips = pd.read_csv(
    r"C:\City Bike\data\processed\citibike_cleaned.csv"
)

# Load cleaned station data
stations = pd.read_csv(
    r"C:\City Bike\notebooks\cleaned_data.csv"
)

# Prepare start-station information
start_stations = stations.rename(columns={
    "station_id": "start_station_id",
    "station_name": "start_station_info_name",
    "latitude": "start_station_info_lat",
    "longitude": "start_station_info_lng"
})

# Prepare end-station information
end_stations = stations.rename(columns={
    "station_id": "end_station_id",
    "station_name": "end_station_info_name",
    "latitude": "end_station_info_lat",
    "longitude": "end_station_info_lng"
})

# Merge station information into trips
merged = trips.merge(
    start_stations,
    on="start_station_id",
    how="left"
).merge(
    end_stations,
    on="end_station_id",
    how="left"
)

# Save merged data
output_path = r"C:\City Bike\data\processed\citibike_trips_with_stations.csv"
merged.to_csv(output_path, index=False)

print("Saved:", output_path)
print("Shape:", merged.shape)

C:\Users\Chinmaya Harekrishna\AppData\Local\Temp\ipykernel_22152\1685014381.py:36: DtypeWarning: Columns (0: start_station_id, 1: end_station_id) have mixed types. Specify dtype option on import or set low_memory=False.
  trips = pd.read_csv(

Saved: C:\City Bike\data\processed\citibike_trips_with_stations.csv
Shape: (5244973, 42)

In [60]:
# Normalize station ID columns
trips["start_station_id"] = trips["start_station_id"].astype("string").str.strip()
trips["end_station_id"] = trips["end_station_id"].astype("string").str.strip()
stations["station_id"] = stations["station_id"].astype("string").str.strip()

# Remove missing station IDs from the station lookup table
stations = stations.dropna(subset=["station_id"]).drop_duplicates(
    subset=["station_id"]
)

# Rename station columns
start_stations = stations.rename(columns={
    "station_id": "start_station_id",
    "station_name": "start_station_info_name",
    "latitude": "start_station_info_lat",
    "longitude": "start_station_info_lng"
})

end_stations = stations.rename(columns={
    "station_id": "end_station_id",
    "station_name": "end_station_info_name",
    "latitude": "end_station_info_lat",
    "longitude": "end_station_info_lng"
})

# Merge
merged = (
    trips
    .merge(start_stations, on="start_station_id", how="left")
    .merge(end_stations, on="end_station_id", how="left")
)

# Check unmatched stations
print("Unmatched start stations:",
      merged["start_station_info_name"].isna().sum())
print("Unmatched end stations:",
      merged["end_station_info_name"].isna().sum())

merged.head()

Unmatched start stations: 5244973
Unmatched end stations: 5244973

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,region_id_y,capacity_y,rental_uris_y,rental_methods_y,has_kiosk_y,station_type_y,external_id_y,electric_bike_surcharge_waiver_y,eightd_station_services_y,eightd_has_key_dispenser_y
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
# Remove rows containing NaN values; columns remain unchanged
merged = merged.dropna(axis=0).reset_index(drop=True)

print("Columns kept:", merged.columns.tolist())
print("Remaining NaN values:", merged.isna().sum().sum())

output_path = r"C:\City Bike\data\processed\citibike_trips_no_nan.csv"
merged.to_csv(output_path, index=False)

print("Saved:", output_path)

Columns kept: ['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual', 'time', 'temperature_2m', 'relative_humidity_2m', 'precipitation', 'wind_speed_10m', 'station_id', 'name', 'short_name_x', 'lon', 'lat', 'region_id_x', 'capacity_x', 'rental_uris_x', 'rental_methods_x', 'has_kiosk_x', 'station_type_x', 'external_id_x', 'electric_bike_surcharge_waiver_x', 'eightd_station_services_x', 'eightd_has_key_dispenser_x', 'station_name', 'short_name_y', 'longitude', 'latitude', 'region_id_y', 'capacity_y', 'rental_uris_y', 'rental_methods_y', 'has_kiosk_y', 'station_type_y', 'external_id_y', 'electric_bike_surcharge_waiver_y', 'eightd_station_services_y', 'eightd_has_key_dispenser_y']
Remaining NaN values: 0
Saved: C:\City Bike\data\processed\citibike_trips_no_nan.csv

In [78]:
import pandas as pd

trips = pd.read_csv(
    r"C:\City Bike\data\processed\citibike_cleaned.csv",
    dtype={"start_station_id": "string", "end_station_id": "string"}
)

stations = pd.read_csv(
    r"C:\City Bike\notebooks\cleaned_data.csv",
    dtype={"station_id": "string"}
)

# Standardize station IDs
def clean_id(series):
    return (
        series.astype("string")
        .str.strip()
        .str.replace(r"\.0$", "", regex=True)
    )

trips["start_station_id"] = clean_id(trips["start_station_id"])
trips["end_station_id"] = clean_id(trips["end_station_id"])
stations["station_id"] = clean_id(stations["station_id"])

stations = stations.dropna(subset=["station_id"]).drop_duplicates("station_id")

start_stations = stations.rename(columns={
    "station_id": "start_station_id",
    "station_name": "start_station_info_name",
    "latitude": "start_station_info_lat",
    "longitude": "start_station_info_lng"
})

end_stations = stations.rename(columns={
    "station_id": "end_station_id",
    "station_name": "end_station_info_name",
    "latitude": "end_station_info_lat",
    "longitude": "end_station_info_lng"
})

merged = (
    trips
    .merge(start_stations, on="start_station_id", how="left")
    .merge(end_stations, on="end_station_id", how="left")
)

# Keep rows and columns; replace missing values
merged = merged.fillna("Unknown")

output_path = r"C:\City Bike\data\processed\citibike_trips_with_stations.csv"
merged.to_csv(output_path, index=False)

print("Rows and columns:", merged.shape)
print("Remaining NaN values:", merged.isna().sum().sum())
print("Saved:", output_path)

Rows and columns: (5244973, 42)
Remaining NaN values: 0
Saved: C:\City Bike\data\processed\citibike_trips_with_stations.csv

In [79]:
merged.isnull().sum()

ride_id                             0
rideable_type                       0
started_at                          0
ended_at                            0
start_station_name                  0
start_station_id                    0
end_station_name                    0
end_station_id                      0
start_lat                           0
start_lng                           0
end_lat                             0
end_lng                             0
member_casual                       0
trip_duration_min                   0
start_station_info_name             0
short_name_x                        0
start_station_info_lng              0
start_station_info_lat              0
region_id_x                         0
capacity_x                          0
rental_uris_x                       0
rental_methods_x                    0
has_kiosk_x                         0
station_type_x                      0
external_id_x                       0
electric_bike_surcharge_waiver_x    0
eightd_station_services_x           0
eightd_has_key_dispenser_x          0
end_station_info_name               0
short_name_y                        0
end_station_info_lng                0
end_station_info_lat                0
region_id_y                         0
capacity_y                          0
rental_uris_y                       0
rental_methods_y                    0
has_kiosk_y                         0
station_type_y                      0
external_id_y                       0
electric_bike_surcharge_waiver_y    0
eightd_station_services_y           0
eightd_has_key_dispenser_y          0
dtype: int64

In [127]:
merged.shape

(5244973, 43)

In [128]:
print(df1.columns.tolist())
print(df2.columns.tolist())

['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual', 'time', 'temperature_2m', 'relative_humidity_2m', 'precipitation', 'wind_speed_10m', 'station_id', 'name', 'short_name', 'lon', 'lat', 'region_id', 'capacity', 'rental_uris', 'rental_methods', 'has_kiosk', 'station_type', 'external_id', 'electric_bike_surcharge_waiver', 'eightd_station_services', 'eightd_has_key_dispenser']
['station_id', 'station_name', 'short_name', 'longitude', 'latitude', 'region_id', 'capacity', 'rental_uris', 'rental_methods', 'has_kiosk', 'station_type', 'external_id', 'electric_bike_surcharge_waiver', 'eightd_station_services', 'eightd_has_key_dispenser']

In [129]:
merged.head(10)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,capacity_y,rental_uris_y,rental_methods_y,has_kiosk_y,station_type_y,external_id_y,electric_bike_surcharge_waiver_y,eightd_station_services_y,eightd_has_key_dispenser_y,date_hour
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-10 14:00:00
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-10 08:00:00
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-08 19:00:00
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-05 14:00:00
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-01 14:00:00
5,53BFB685F8A54E30,electric_bike,2026-08-10 19:02:52.879,2026-08-10 19:27:15.377,5 Ave & E 87 St,7323.09,W 24 St & 7 Ave,6257.03,40.782323,-73.959875,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-10 19:00:00
6,39E6B40AE107AFDB,classic_bike,2026-08-08 20:09:28.645,2026-08-08 20:31:54.176,5 Ave & E 87 St,7323.09,E 89 St & 3 Ave,7265.10,40.782323,-73.959875,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-08 20:00:00
7,2C5C3A8E08BE187B,classic_bike,2026-08-13 20:24:30.697,2026-08-13 20:31:32.058,5 Ave & E 87 St,7323.09,E 89 St & 3 Ave,7265.10,40.782323,-73.959875,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-13 20:00:00
8,6B7246BF25A514AA,classic_bike,2026-08-01 13:45:17.796,2026-08-01 13:52:52.916,37 St & Fort Hamilton Pkwy,3099.01,Parade Pl & Crooke Ave,3376.02,40.644170,-73.989230,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-01 13:00:00
9,BEA885CFAF4474BA,electric_bike,2026-08-04 12:20:51.744,2026-08-04 12:29:21.135,Westchester Ave & E 156 St,7891.06,Morris Ave & E 142 St,7821.01,40.817802,-73.905203,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-04 12:00:00

In [130]:
merged.tail(10)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,capacity_y,rental_uris_y,rental_methods_y,has_kiosk_y,station_type_y,external_id_y,electric_bike_surcharge_waiver_y,eightd_station_services_y,eightd_has_key_dispenser_y,date_hour
5244963,01D18E7AFC43BDC9,electric_bike,2026-08-31 12:17:13.397,2026-08-31 12:32:37.442,Pacific St & Nevins St,4362.04,Halsey St & Tompkins Ave,4319.07,40.685376,-73.983021,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-31 12:00:00
5244964,0D65982086878AE6,electric_bike,2026-08-31 11:41:05.567,2026-08-31 11:49:11.972,Pacific St & Nevins St,4362.04,Carroll St & Columbia St,4348.07,40.685376,-73.983021,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-31 11:00:00
5244965,02009F07CF5D4D71,electric_bike,2026-08-29 16:23:46.232,2026-08-29 17:11:33.412,Kent Ave & N 7 St,5489.03,Van Brunt St & Van Dyke St,4095.10,40.720368,-73.961651,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-29 16:00:00
5244966,0C81C48DA2BA7D80,electric_bike,2026-08-31 18:12:24.556,2026-08-31 18:16:31.075,Greene Ave & Nostrand Ave,4519.02,Halsey St & Tompkins Ave,4319.07,40.688334,-73.950916,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-31 18:00:00
5244967,69497BEEBE90A152,classic_bike,2026-08-31 10:59:02.917,2026-08-31 11:07:42.893,Cliff St & Fulton St,5065.14,Market St & Henry St,5270.09,40.708380,-74.004950,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-31 10:00:00
5244968,7778C182C86ED253,electric_bike,2026-08-29 16:40:59.109,2026-08-29 16:52:10.441,Caton Ave & Argyle Rd,3303.03,West Drive & Prospect Park West,3651.04,40.649681,-73.967829,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-29 16:00:00
5244969,7E1978AE88707549,electric_bike,2026-08-30 14:40:57.513,2026-08-30 14:45:19.773,Lexington Ave & E 26 St,6089.08,E 39 St & Lexington Ave,6389.09,40.741459,-73.983293,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-30 14:00:00
5244970,EE79B9E27476A26B,electric_bike,2026-08-29 17:44:45.322,2026-08-29 18:18:35.303,Kent Ave & N 7 St,5489.03,West Drive & Prospect Park West,3651.04,40.720368,-73.961651,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-29 17:00:00
5244971,2C83FD498727AFDD,electric_bike,2026-08-31 17:26:01.392,2026-08-31 17:36:15.940,E 31 St & 3 Ave,6239.08,W 39 St & 9 Ave,6644.04,40.743943,-73.979661,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-31 17:00:00
5244972,A0A5A6D9CB904049,electric_bike,2026-08-30 15:43:45.477,2026-08-30 16:18:26.236,Lawrence St & Willoughby St,4596.09,Van Brunt St & Van Dyke St,4095.10,40.692362,-73.986317,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,2026-08-30 15:00:00

In [131]:
merged.duplicated().sum()

np.int64(0)

In [132]:
# Keep all rows and columns, replacing missing values
merged = merged.fillna("Unknown")

output_path = r"C:\City Bike\data\processed\citibike_trips_with_stations.csv"

merged.to_csv(output_path, index=False)

print("Data saved successfully:", output_path)
print("Rows and columns:", merged.shape)
print("Remaining missing values:", merged.isna().sum().sum())

Data saved successfully: C:\City Bike\data\processed\citibike_trips_with_stations.csv
Rows and columns: (5244973, 43)
Remaining missing values: 0

In [133]:
import pandas as pd

weather_path = r"C:\City Bike\data\external\nyc_weather.csv"

weather = pd.read_csv(weather_path)

print("Weather data loaded:", weather.shape)
weather.head()

Weather data loaded: (2208, 5)

,time,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m
0,2024-06-01 00:00:00,15.9,52,0.0,10.4
1,2024-06-01 01:00:00,14.4,58,0.0,9.2
2,2024-06-01 02:00:00,13.7,61,0.0,8.9
3,2024-06-01 03:00:00,13.2,63,0.0,8.7
4,2024-06-01 04:00:00,13.3,61,0.0,10.3

In [134]:
weather.tail()

,time,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m
2203,2024-08-31 19:00:00,23.5,74,0.0,14.7
2204,2024-08-31 20:00:00,22.4,81,0.0,12.6
2205,2024-08-31 21:00:00,21.9,88,0.0,10.9
2206,2024-08-31 22:00:00,21.8,87,0.0,10.8
2207,2024-08-31 23:00:00,21.6,88,0.0,10.1

In [135]:
weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 2208 entries, 0 to 2207
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  2208 non-null   str
 1   temperature_2m        2208 non-null   float64
 2   relative_humidity_2m  2208 non-null   int64
 3   precipitation         2208 non-null   float64
 4   wind_speed_10m        2208 non-null   float64
dtypes: float64(3), int64(1), str(1)
memory usage: 86.4 KB

In [136]:
df.shape

(2520, 15)

In [137]:
weather.isnull().sum()

time                    0
temperature_2m          0
relative_humidity_2m    0
precipitation           0
wind_speed_10m          0
dtype: int64

In [138]:
weather.duplicated().sum()

np.int64(0)

In [139]:



weather["time"] = pd.to_datetime(weather["time"], errors="coerce")
weather["date_hour"] = weather["time"].dt.floor("h")

merged["started_at"] = pd.to_datetime(merged["started_at"], errors="coerce")
merged["date_hour"] = merged["started_at"].dt.floor("h")

# Merge trips with weather
final_df = merged.merge(
    weather,
    on="date_hour",
    how="left"
)



 
output_path = r"C:\City Bike\data\processed\citibike_final_with_weather.csv"
final_df.to_csv(output_path, index=False)

print("CSV saved:", output_path)
print("Rows and columns:", final_df.shape)

final_df.head()

CSV saved: C:\City Bike\data\processed\citibike_final_with_weather.csv
Rows and columns: (5244973, 48)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,external_id_y,electric_bike_surcharge_waiver_y,eightd_station_services_y,eightd_has_key_dispenser_y,date_hour,time,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,...,Unknown,Unknown,Unknown,Unknown,2026-08-10 14:00:00,NaT,NaN,NaN,NaN,NaN
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,...,Unknown,Unknown,Unknown,Unknown,2026-08-10 08:00:00,NaT,NaN,NaN,NaN,NaN
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,...,Unknown,Unknown,Unknown,Unknown,2026-08-08 19:00:00,NaT,NaN,NaN,NaN,NaN
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,Unknown,Unknown,Unknown,Unknown,2026-08-05 14:00:00,NaT,NaN,NaN,NaN,NaN
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,Unknown,Unknown,Unknown,Unknown,2026-08-01 14:00:00,NaT,NaN,NaN,NaN,NaN

In [140]:
import os
import pandas as pd

# Prepare weather data
weather["time"] = pd.to_datetime(weather["time"], errors="coerce")
weather["date_hour"] = weather["time"].dt.floor("h")

# Prepare merged trip and station data
merged["started_at"] = pd.to_datetime(merged["started_at"], errors="coerce")
merged["date_hour"] = merged["started_at"].dt.floor("h")

# Merge trips + stations + weather
final_df = merged.merge(
    weather,
    on="date_hour",
    how="left"
)

# Save everything as one CSV file
output_path = r"C:\City Bike\data\processed\citibike_all_data.csv"
os.makedirs(os.path.dirname(output_path), exist_ok=True)

final_df.to_csv(output_path, index=False)

print("All data merged and saved:", output_path)
print("Rows and columns:", final_df.shape)

final_df.head()

All data merged and saved: C:\City Bike\data\processed\citibike_all_data.csv
Rows and columns: (5244973, 48)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,external_id_y,electric_bike_surcharge_waiver_y,eightd_station_services_y,eightd_has_key_dispenser_y,date_hour,time,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,...,Unknown,Unknown,Unknown,Unknown,2026-08-10 14:00:00,NaT,NaN,NaN,NaN,NaN
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,...,Unknown,Unknown,Unknown,Unknown,2026-08-10 08:00:00,NaT,NaN,NaN,NaN,NaN
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,...,Unknown,Unknown,Unknown,Unknown,2026-08-08 19:00:00,NaT,NaN,NaN,NaN,NaN
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,Unknown,Unknown,Unknown,Unknown,2026-08-05 14:00:00,NaT,NaN,NaN,NaN,NaN
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,Unknown,Unknown,Unknown,Unknown,2026-08-01 14:00:00,NaT,NaN,NaN,NaN,NaN

In [141]:
final_df.shape

(5244973, 48)

In [142]:
final_df.isnull().sum()

ride_id                                   0
rideable_type                             0
started_at                                0
ended_at                                  0
start_station_name                        0
start_station_id                          0
end_station_name                          0
end_station_id                            0
start_lat                                 0
start_lng                                 0
end_lat                                   0
end_lng                                   0
member_casual                             0
trip_duration_min                         0
start_station_info_name                   0
short_name_x                              0
start_station_info_lng                    0
start_station_info_lat                    0
region_id_x                               0
capacity_x                                0
rental_uris_x                             0
rental_methods_x                          0
has_kiosk_x                               0
station_type_x                            0
external_id_x                             0
electric_bike_surcharge_waiver_x          0
eightd_station_services_x                 0
eightd_has_key_dispenser_x                0
end_station_info_name                     0
short_name_y                              0
end_station_info_lng                      0
end_station_info_lat                      0
region_id_y                               0
capacity_y                                0
rental_uris_y                             0
rental_methods_y                          0
has_kiosk_y                               0
station_type_y                            0
external_id_y                             0
electric_bike_surcharge_waiver_y          0
eightd_station_services_y                 0
eightd_has_key_dispenser_y                0
date_hour                                 0
time                                5244973
temperature_2m                      5244973
relative_humidity_2m                5244973
precipitation                       5244973
wind_speed_10m                      5244973
dtype: int64

In [143]:
# Create time features
final_df["started_at"] = pd.to_datetime(
    final_df["started_at"],
    errors="coerce"
)

final_df["hour"] = final_df["started_at"].dt.hour
final_df["day_of_week"] = final_df["started_at"].dt.day_name()
final_df["is_weekend"] = final_df["started_at"].dt.dayofweek >= 5

# Save final data
output_path = r"C:\City Bike\data\processed\citibike_all_data.csv"
final_df.to_csv(output_path, index=False)

print("Saved:", output_path)
final_df.head()

Saved: C:\City Bike\data\processed\citibike_all_data.csv

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,eightd_has_key_dispenser_y,date_hour,time,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m,hour,day_of_week,is_weekend
0,E4A8132DACF670C3,electric_bike,2026-08-10 14:31:22.100,2026-08-10 14:37:37.034,E 33 St & 5 Ave,6322.01,W 24 St & 7 Ave,6257.03,40.747659,-73.984907,...,Unknown,2026-08-10 14:00:00,NaT,NaN,NaN,NaN,NaN,14,Monday,False
1,8382768C05C30BB4,electric_bike,2026-08-10 08:04:28.348,2026-08-10 08:33:27.680,Emerson Pl & Myrtle Ave,4683.02,W 24 St & 7 Ave,6257.03,40.693631,-73.962236,...,Unknown,2026-08-10 08:00:00,NaT,NaN,NaN,NaN,NaN,8,Monday,False
2,3A1C43832BBE4FCD,classic_bike,2026-08-08 19:36:32.350,2026-08-08 19:43:47.890,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,...,Unknown,2026-08-08 19:00:00,NaT,NaN,NaN,NaN,NaN,19,Saturday,True
3,5C9BC6DFC4DEA183,electric_bike,2026-08-05 14:34:27.749,2026-08-05 14:46:23.526,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,Unknown,2026-08-05 14:00:00,NaT,NaN,NaN,NaN,NaN,14,Wednesday,False
4,355579CC64D1BE20,electric_bike,2026-08-01 14:16:44.531,2026-08-01 14:29:39.539,Sterling Pl & Bedford Ave,3993.03,Cumberland St & Lafayette Ave,4428.02,40.672695,-73.954131,...,Unknown,2026-08-01 14:00:00,NaT,NaN,NaN,NaN,NaN,14,Saturday,True

In [144]:
# Create time features
final_df["started_at"] = pd.to_datetime(
    final_df["started_at"],
    errors="coerce"
)

final_df["hour"] = final_df["started_at"].dt.hour
final_df["day_of_week"] = final_df["started_at"].dt.day_name()
final_df["is_weekend"] = final_df["started_at"].dt.dayofweek >= 5

In [147]:
final_df.isnull().sum()

ride_id              0
rideable_type        0
started_at           0
ended_at             0
trip_duration_min    0
trip_distance_km     0
member_casual        0
dtype: int64

In [148]:
df.shape

(2520, 15)

In [151]:
final_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'trip_duration_min', 'trip_distance_km', 'member_casual'],
      dtype='str')

In [152]:
import os

output_path = r"C:\City Bike\data\processed\citibike_final_cleaned.csv"
os.makedirs(os.path.dirname(output_path), exist_ok=True)

final_df.to_csv(output_path, index=False)

print("Data saved successfully:", output_path)
print("Shape:", final_df.shape)

Data saved successfully: C:\City Bike\data\processed\citibike_final_cleaned.csv
Shape: (5244973, 7)